name = "astro-app"
compatibility_date = "2024-01-01"

# Main entry point for the Worker (Astro's _worker.js)
main = "./dist/_worker.js"

# Static assets configuration
[assets]
directory = "./dist"

# Optional: Enable preview URLs
preview_urls = true

# Optional: Use workers.dev subdomain
workers_dev = true

# Production environment configuration
[env.production]
name = "astro-app-production"

# Build configuration
[build]
command = "npm run build"

# Pages build output directory
[pages]
publish = "dist/"