name = "luna"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

# Build configuration
[build]
command = "npm run build"